from collections.abc import Iterable

import httpx

from config import settings
from models import RcaRequest, RcaResponse, SimilarIncident


class RcaGenerator:
    async def generate(self, request: RcaRequest, similar: list[SimilarIncident]) -> RcaResponse:
        if settings.use_ollama:
            generated = await self._try_ollama(request, similar)
            if generated:
                return generated
        return self._deterministic_rca(request, similar)

    async def _try_ollama(
        self, request: RcaRequest, similar: list[SimilarIncident]
    ) -> RcaResponse | None:
        prompt = self._prompt(request, similar)
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                response = await client.post(
                    f"{settings.ollama_url}/api/generate",
                    json={"model": settings.ollama_model, "prompt": prompt, "stream": False},
                )
                response.raise_for_status()
                text = response.json().get("response", "").strip()
        except Exception:
            return None
        if not text:
            return None
        return RcaResponse(
            incidentId=request.incidentId,
            summary=text,
            likelyRootCause="Generated by Ollama from incident context and retrieved memory.",
            evidence=self._evidence(request, similar),
            remediation=self._remediation(request),
        )

    def _deterministic_rca(self, request: RcaRequest, similar: list[SimilarIncident]) -> RcaResponse:
        matching_services = sorted({item.service for item in similar})
        likely_root = "Insufficient evidence for a single root cause."
        query = request.query.lower()
        if "redis" in query and ("latency" in query or "timeout" in query):
            likely_root = "Redis saturation or connectivity regression after a deployment."
        elif "oom" in query or "crashloop" in query:
            likely_root = "Container memory pressure causing repeated pod restarts."
        elif "deployment" in query:
            likely_root = "Recent deployment changed runtime behavior for the affected service."

        summary = (
            f"AEGIS analyzed current telemetry plus {len(similar)} retrieved historical incidents. "
            f"Related services: {', '.join(matching_services) if matching_services else 'none yet'}."
        )
        return RcaResponse(
            incidentId=request.incidentId,
            summary=summary,
            likelyRootCause=likely_root,
            evidence=self._evidence(request, similar),
            remediation=self._remediation(request),
        )

    def _evidence(self, request: RcaRequest, similar: list[SimilarIncident]) -> list[str]:
        evidence = []
        evidence.extend(self._take(request.logs or [], 3))
        for key, value in (request.telemetry or {}).items():
            evidence.append(f"telemetry {key}={value}")
        for item in similar[:3]:
            evidence.append(f"similar incident {item.incidentId}: {item.summary}")
        return evidence or ["No high-confidence evidence supplied yet."]

    @staticmethod
    def _remediation(request: RcaRequest) -> list[str]:
        query = request.query.lower()
        if "redis" in query:
            return [
                "Inspect Redis connection pool saturation and server latency.",
                "Compare deployment configuration against the last healthy version.",
                "Temporarily scale dependent consumers or reduce retry pressure.",
            ]
        if "oom" in query or "crashloop" in query:
            return [
                "Check pod memory limits, heap sizing, and recent allocation changes.",
                "Rollback the deployment if restart rate is still increasing.",
                "Capture heap/profile data before increasing limits permanently.",
            ]
        return [
            "Validate recent deployment and configuration changes.",
            "Correlate logs, metrics, and events over the incident time window.",
            "Open a follow-up graph investigation for upstream and downstream services.",
        ]

    @staticmethod
    def _take(values: Iterable[str], limit: int) -> list[str]:
        return [value for index, value in enumerate(values) if index < limit]

    @staticmethod
    def _prompt(request: RcaRequest, similar: list[SimilarIncident]) -> str:
        related = "\n".join(f"- {item.incidentId}: {item.summary}" for item in similar)
        logs = "\n".join(request.logs or [])
        telemetry = "\n".join(f"{key}: {value}" for key, value in (request.telemetry or {}).items())
        return f"""
You are AEGIS, an infrastructure RCA engine. Produce a concise RCA with root cause,
evidence, and remediation. Do not act like a chatbot.

Current investigation:
{request.query}

Logs:
{logs}

Telemetry:
{telemetry}

Similar incidents:
{related}
"""
