from dataclasses import dataclass
from collections.abc import Iterable

import httpx

from config import settings
from models import RcaRequest, RcaResponse, SimilarIncident


@dataclass
class DeterministicAnalysis:
    pattern: str
    likely_root: str
    summary_hint: str
    remediation: list[str]
    telemetry_focus: list[str]
    score: int


class RcaGenerator:
    async def generate(self, request: RcaRequest, similar: list[SimilarIncident]) -> RcaResponse:
        if settings.use_ollama:
            generated = await self._try_ollama(request, similar)
            if generated:
                return generated
        return self._deterministic_rca(request, similar)

    async def _try_ollama(
        self, request: RcaRequest, similar: list[SimilarIncident]
    ) -> RcaResponse | None:
        prompt = self._prompt(request, similar)
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                response = await client.post(
                    f"{settings.ollama_url}/api/generate",
                    json={"model": settings.ollama_model, "prompt": prompt, "stream": False},
                )
                response.raise_for_status()
                text = response.json().get("response", "").strip()
        except Exception:
            return None
        if not text:
            return None
        return RcaResponse(
            incidentId=request.incidentId,
            summary=text,
            likelyRootCause="Generated by Ollama from incident context and retrieved memory.",
            evidence=self._evidence(request, similar),
            remediation=self._remediation(self._analyze(request, similar)),
        )

    def _deterministic_rca(self, request: RcaRequest, similar: list[SimilarIncident]) -> RcaResponse:
        analysis = self._analyze(request, similar)
        matching_services = sorted({item.service for item in similar})
        service = self._extract_labeled_value(request.query, "service")
        deployment = self._extract_labeled_value(request.query, "deployment")
        live_signals = self._signal_snapshot(request.telemetry or {}, analysis.telemetry_focus, 3)

        summary = (
            f"AEGIS analyzed the live incident"
            f"{f' on {service}' if service else ''}"
            f"{f' ({deployment})' if deployment else ''}. "
            f"The active failure pattern is {analysis.summary_hint}. "
            f"Strongest live signals: {live_signals or 'logs and telemetry are still sparse'}. "
            f"Related historical services: {', '.join(matching_services) if matching_services else 'none yet'}."
        )
        return RcaResponse(
            incidentId=request.incidentId,
            summary=summary,
            likelyRootCause=analysis.likely_root,
            evidence=self._evidence(request, similar),
            remediation=self._remediation(analysis),
        )

    def _evidence(self, request: RcaRequest, similar: list[SimilarIncident]) -> list[str]:
        evidence = []
        evidence.extend(self._take(request.logs or [], 3))
        for key, value in self._prioritized_telemetry_items(request.telemetry or {}):
            evidence.append(f"telemetry {key}={value}")
        for item in similar[:3]:
            if item.rootCause:
                evidence.append(f"similar incident {item.incidentId}: {item.summary}; root cause {item.rootCause}")
            else:
                evidence.append(f"similar incident {item.incidentId}: {item.summary}")
        return evidence or ["No high-confidence evidence supplied yet."]

    def _analyze(self, request: RcaRequest, similar: list[SimilarIncident]) -> DeterministicAnalysis:
        text = " ".join(
            filter(
                None,
                [
                    request.query,
                    *(request.logs or []),
                    *(item.summary for item in similar),
                    *(item.rootCause or "" for item in similar),
                ],
            )
        ).lower()
        telemetry = request.telemetry or {}

        scores = {
            "redis": 0,
            "queue": 0,
            "memory": 0,
            "provider": 0,
            "deployment": 0,
            "timeout": 0,
        }

        if "redis" in text:
            scores["redis"] += 3
        if any(term in text for term in ("connection pool", "pool exhausted", "cache timeout")):
            scores["redis"] += 2
        if any("redis" in key for key in telemetry):
            scores["redis"] += 3
        if self._metric_value(telemetry, "redis_latency_ms") >= 500:
            scores["redis"] += 2
        if self._metric_value(telemetry, "retry_rate") >= 10:
            scores["redis"] += 1

        if any(term in text for term in ("consumer lag", "topic lag", "queue backlog", "kafka", "orders topic")):
            scores["queue"] += 3
        if any("lag" in key for key in telemetry):
            scores["queue"] += 3
        if self._metric_value(telemetry, "queue_depth") >= 1000:
            scores["queue"] += 2
        if any(term in text for term in ("downstream timeout budget exhausted", "bulk import", "sync backlog")):
            scores["queue"] += 2

        if any(term in text for term in ("oom", "crashloop", "heap", "memory pressure", "oomkilled")):
            scores["memory"] += 3
        if self._metric_value(telemetry, "restart_count") >= 1:
            scores["memory"] += 2
        if max(
            self._metric_value(telemetry, "memory_percent"),
            self._metric_value(telemetry, "memory_working_set_ratio") * 100,
        ) >= 85:
            scores["memory"] += 2

        if any(term in text for term in ("provider throttled", "provider throttling", "rate limit", "campaign")):
            scores["provider"] += 3
        if self._metric_value(telemetry, "provider_latency_ms") >= 1000:
            scores["provider"] += 2

        if "deployment" in text or "config" in text or "rollout" in text:
            scores["deployment"] += 2
        if " v" in text:
            scores["deployment"] += 1

        if any(term in text for term in ("timeout", "latency", "degradation")):
            scores["timeout"] += 2
        if self._metric_value(telemetry, "p95_latency_ms") >= 1500:
            scores["timeout"] += 2
        if self._metric_value(telemetry, "error_rate") >= 0.05:
            scores["timeout"] += 1

        top_pattern = max(scores, key=scores.get)
        top_score = scores[top_pattern]

        if top_score <= 0:
            return DeterministicAnalysis(
                pattern="generic",
                likely_root="Current evidence is mixed, but the incident is actively degrading the service.",
                summary_hint="mixed service degradation without a single dominant failure signal yet",
                remediation=[
                    "Validate the latest deployment and configuration changes for the affected service.",
                    "Correlate the incident timeline across logs, metrics, and upstream or downstream dependencies.",
                    "Capture a fresh telemetry snapshot before making a rollback decision.",
                ],
                telemetry_focus=["error_rate", "p95_latency_ms", "queue_depth"],
                score=0,
            )

        analyses = {
            "redis": DeterministicAnalysis(
                pattern="redis",
                likely_root="Redis saturation or connection pool exhaustion is degrading service calls after the current rollout.",
                summary_hint="a cache or connection-pool bottleneck causing retries and latency growth",
                remediation=[
                    "Inspect Redis saturation, connection pool usage, and timeout rates on the affected service.",
                    "Compare the current rollout or config with the last healthy release, especially connection reuse settings.",
                    "Reduce retry pressure or scale consumers temporarily while Redis latency recovers.",
                ],
                telemetry_focus=["redis_latency_ms", "retry_rate", "error_rate", "p95_latency_ms"],
                score=top_score,
            ),
            "queue": DeterministicAnalysis(
                pattern="queue",
                likely_root="Consumer lag and queue backlog are propagating into synchronous request timeouts.",
                summary_hint="a queue backlog that is now spilling into request latency and downstream timeouts",
                remediation=[
                    "Scale or recover the lagging consumers and identify which partition or topic is falling behind.",
                    "Throttle or pause the upstream producer that is growing queue depth until consumers catch up.",
                    "Tighten alerts on lag, queue depth, and timeout budget before reopening full traffic.",
                ],
                telemetry_focus=["consumer_lag", "queue_depth", "p95_latency_ms", "error_rate"],
                score=top_score,
            ),
            "memory": DeterministicAnalysis(
                pattern="memory",
                likely_root="Container memory pressure is triggering restarts and destabilizing the workload.",
                summary_hint="memory pressure leading to restarts, heap growth, and degraded processing",
                remediation=[
                    "Check pod memory limits, heap sizing, batch size, and recent allocation changes.",
                    "Rollback or reduce workload intensity if restart count is still climbing.",
                    "Capture heap or allocation profiles before permanently raising limits.",
                ],
                telemetry_focus=["restart_count", "memory_percent", "p95_latency_ms", "queue_depth"],
                score=top_score,
            ),
            "provider": DeterministicAnalysis(
                pattern="provider",
                likely_root="An external provider is throttling requests and amplifying retry-driven latency.",
                summary_hint="provider-side throttling that is inflating retries and delayed delivery",
                remediation=[
                    "Fail over to the secondary provider or reduce outbound send rate immediately.",
                    "Rate-limit burst traffic from the campaign or notification producer.",
                    "Replay delayed or failed messages only after provider error rates stabilize.",
                ],
                telemetry_focus=["provider_latency_ms", "retry_rate", "queue_depth", "error_rate"],
                score=top_score,
            ),
            "deployment": DeterministicAnalysis(
                pattern="deployment",
                likely_root="A recent deployment or configuration change likely altered runtime behavior for the affected service.",
                summary_hint="runtime degradation introduced close to a deployment or config change",
                remediation=[
                    "Diff the current deployment and config against the last known healthy version.",
                    "Verify whether the incident started immediately after rollout and isolate the changed component.",
                    "Rollback or disable the changed configuration if latency and error rate are still rising.",
                ],
                telemetry_focus=["p95_latency_ms", "error_rate", "queue_depth"],
                score=top_score,
            ),
            "timeout": DeterministicAnalysis(
                pattern="timeout",
                likely_root="A downstream timeout cascade is driving the observed latency and error-rate spike.",
                summary_hint="latency and timeout amplification across a service dependency chain",
                remediation=[
                    "Identify the slow downstream dependency and inspect its saturation or timeout budget.",
                    "Lower retry fanout and protect the request path with tighter circuit breaking.",
                    "Trace the dependency chain over the incident window to confirm where latency first spiked.",
                ],
                telemetry_focus=["p95_latency_ms", "error_rate", "queue_depth"],
                score=top_score,
            ),
        }
        return analyses[top_pattern]

    @staticmethod
    def _remediation(analysis: DeterministicAnalysis) -> list[str]:
        return analysis.remediation

    @staticmethod
    def _extract_labeled_value(text: str, label: str) -> str | None:
        prefix = f"{label.lower()}:"
        for line in text.splitlines():
            lowered = line.lower()
            if lowered.startswith(prefix):
                return line.split(":", 1)[1].strip() or None
        return None

    def _signal_snapshot(self, telemetry: dict[str, object], focus: list[str], limit: int) -> str:
        prioritized = self._prioritized_telemetry_items(telemetry, focus)
        return ", ".join(f"{key}={value}" for key, value in prioritized[:limit])

    def _prioritized_telemetry_items(
        self, telemetry: dict[str, object], focus: list[str] | None = None
    ) -> list[tuple[str, object]]:
        if not telemetry:
            return []
        focus = focus or []
        focused = [(key, telemetry[key]) for key in focus if key in telemetry]
        remaining = [(key, value) for key, value in telemetry.items() if key not in {item[0] for item in focused}]
        return focused + remaining

    @staticmethod
    def _metric_value(telemetry: dict[str, object], key: str) -> float:
        value = telemetry.get(key)
        if isinstance(value, str):
            try:
                return float(value.strip("%"))
            except ValueError:
                return 0.0
        if isinstance(value, bool):
            return float(value)
        if isinstance(value, (int, float)):
            return float(value)
        return 0.0

    @staticmethod
    def _take(values: Iterable[str], limit: int) -> list[str]:
        return [value for index, value in enumerate(values) if index < limit]

    @staticmethod
    def _prompt(request: RcaRequest, similar: list[SimilarIncident]) -> str:
        related = "\n".join(f"- {item.incidentId}: {item.summary}" for item in similar)
        logs = "\n".join(request.logs or [])
        telemetry = "\n".join(f"{key}: {value}" for key, value in (request.telemetry or {}).items())
        return f"""
You are AEGIS, an infrastructure RCA engine. Produce a concise RCA with root cause,
evidence, and remediation. Do not act like a chatbot.

Current investigation:
{request.query}

Logs:
{logs}

Telemetry:
{telemetry}

Similar incidents:
{related}
"""
